import { Montserrat } from '@next/font/google';

import '@/app/globals.css';

import type { Metadata } from 'next';

const montserrat = Montserrat({
    weight: ['400', '700'],
    subsets: ['latin'],
    variable: '--font-montserrat',
});

export const metadata: Metadata = {
    title: 'Forukara',
    description: 'Generated by create next app',
    viewport: 'width=device-width, initial-scale=1',
    icons: '/favicon.ico',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body className={`${montserrat.className}`}>{children}</body>
        </html>
    );
}
