export const LANGUAGES = [
    { value: "Abkhazian", label: "Abkhazian" },
    { value: "Afar", label: "Afar" },
    { value: "Afrikaans", label: "Afrikaans" },
    { value: "Akan", label: "Akan" },
    { value: "Albanian", label: "Albanian" },
    { value: "Amharic", label: "Amharic" },
    { value: "Arabic", label: "Arabic" },
    { value: "Aragonese", label: "Aragonese" },
    { value: "Armenian", label: "Armenian" },
    { value: "Assamese", label: "Assamese" },
    { value: "Avaric", label: "Avaric" },
    { value: "Avestan", label: "Avestan" },
    { value: "Aymara", label: "Aymara" },
    { value: "Azerbaijani", label: "Azerbaijani" },
    { value: "Bambara", label: "Bambara" },
    { value: "Bashkir", label: "Bashkir" },
    { value: "Basque", label: "Basque" },
    { value: "Belarusian", label: "Belarusian" },
    { value: "Bengali", label: "Bengali" },
    { value: "Bihari languages", label: "Bihari languages" },
    { value: "Bislama", label: "Bislama" },
    { value: "Bosnian", label: "Bosnian" },
    { value: "Breton", label: "Breton" },
    { value: "Bulgarian", label: "Bulgarian" },
    { value: "Burmese", label: "Burmese" },
    { value: "Cantonese", label: "Cantonese" },
    { value: "Catalan, Valencian", label: "Catalan, Valencian" },
    { value: "Central Khmer", label: "Central Khmer" },
    { value: "Chamorro", label: "Chamorro" },
    { value: "Chechen", label: "Chechen" },
    { value: "Chichewa, Chewa, Nyanja", label: "Chichewa, Chewa, Nyanja" },
    { value: "Church Slavonic, Old Bulgarian, Old Church Slavonic", label: "Church Slavonic, Old Bulgarian, Old Church Slavonic" },
    { value: "Chuvash", label: "Chuvash" },
    { value: "Cornish", label: "Cornish" },
    { value: "Corsican", label: "Corsican" },
    { value: "Cree", label: "Cree" },
    { value: "Croatian", label: "Croatian" },
    { value: "Czech", label: "Czech" },
    { value: "Danish", label: "Danish" },
    { value: "Divehi, Dhivehi, Maldivian", label: "Divehi, Dhivehi, Maldivian" },
    { value: "Dutch, Flemish", label: "Dutch, Flemish" },
    { value: "Dzongkha", label: "Dzongkha" },
    { value: "English", label: "English" },
    { value: "Esperanto", label: "Esperanto" },
    { value: "Estonian", label: "Estonian" },
    { value: "Ewe", label: "Ewe" },
    { value: "Faroese", label: "Faroese" },
    { value: "Fijian", label: "Fijian" },
    { value: "Finnish", label: "Finnish" },
    { value: "French", label: "French" },
    { value: "Fulah", label: "Fulah" },
    { value: "Gaelic, Scottish Gaelic", label: "Gaelic, Scottish Gaelic" },
    { value: "Galician", label: "Galician" },
    { value: "Ganda", label: "Ganda" },
    { value: "Georgian", label: "Georgian" },
    { value: "German", label: "German" },
    { value: "Gikuyu, Kikuyu", label: "Gikuyu, Kikuyu" },
    { value: "Greek (Modern)", label: "Greek (Modern)" },
    { value: "Greenlandic, Kalaallisut", label: "Greenlandic, Kalaallisut" },
    { value: "Guarani", label: "Guarani" },
    { value: "Gujarati", label: "Gujarati" },
    { value: "Haitian, Haitian Creole", label: "Haitian, Haitian Creole" },
    { value: "Hausa", label: "Hausa" },
    { value: "Hebrew", label: "Hebrew" },
    { value: "Herero", label: "Herero" },
    { value: "Hindi", label: "Hindi" },
    { value: "Hiri Motu", label: "Hiri Motu" },
    { value: "Hungarian", label: "Hungarian" },
    { value: "Icelandic", label: "Icelandic" },
    { value: "Ido", label: "Ido" },
    { value: "Igbo", label: "Igbo" },
    { value: "Indonesian", label: "Indonesian" },
    { value: "Interlingua (International Auxiliary Language Association)", label: "Interlingua (International Auxiliary Language Association)" },
    { value: "Interlingue", label: "Interlingue" },
    { value: "Inuktitut", label: "Inuktitut" },
    { value: "Inupiaq", label: "Inupiaq" },
    { value: "Irish", label: "Irish" },
    { value: "Italian", label: "Italian" },
    { value: "Japanese", label: "Japanese" },
    { value: "Javanese", label: "Javanese" },
    { value: "Kannada", label: "Kannada" },
    { value: "Kanuri", label: "Kanuri" },
    { value: "Kashmiri", label: "Kashmiri" },
    { value: "Kazakh", label: "Kazakh" },
    { value: "Kinyarwanda", label: "Kinyarwanda" },
    { value: "Komi", label: "Komi" },
    { value: "Kongo", label: "Kongo" },
    { value: "Korean", label: "Korean" },
    { value: "Kwanyama, Kuanyama", label: "Kwanyama, Kuanyama" },
    { value: "Kurdish", label: "Kurdish" },
    { value: "Kyrgyz", label: "Kyrgyz" },
    { value: "Lao", label: "Lao" },
    { value: "Latin", label: "Latin" },
    { value: "Latvian", label: "Latvian" },
    { value: "Letzeburgesch, Luxembourgish", label: "Letzeburgesch, Luxembourgish" },
    { value: "Limburgish, Limburgan, Limburger", label: "Limburgish, Limburgan, Limburger" },
    { value: "Lingala", label: "Lingala" },
    { value: "Lithuanian", label: "Lithuanian" },
    { value: "Luba-Katanga", label: "Luba-Katanga" },
    { value: "Mandarin", label: "Mandarin" },
    { value: "Macedonian", label: "Macedonian" },
    { value: "Malagasy", label: "Malagasy" },
    { value: "Malay", label: "Malay" },
    { value: "Malayalam", label: "Malayalam" },
    { value: "Maltese", label: "Maltese" },
    { value: "Manx", label: "Manx" },
    { value: "Maori", label: "Maori" },
    { value: "Marathi", label: "Marathi" },
    { value: "Marshallese", label: "Marshallese" },
    { value: "Moldovan, Moldavian, Romanian", label: "Moldovan, Moldavian, Romanian" },
    { value: "Mongolian", label: "Mongolian" },
    { value: "Nauru", label: "Nauru" },
    { value: "Navajo, Navaho", label: "Navajo, Navaho" },
    { value: "Northern Ndebele", label: "Northern Ndebele" },
    { value: "Ndonga", label: "Ndonga" },
    { value: "Nepali", label: "Nepali" },
    { value: "Northern Sami", label: "Northern Sami" },
    { value: "Norwegian", label: "Norwegian" },
    { value: "Norwegian Bokmål", label: "Norwegian Bokmål" },
    { value: "Norwegian Nynorsk", label: "Norwegian Nynorsk" },
    { value: "Nuosu, Sichuan Yi", label: "Nuosu, Sichuan Yi" },
    { value: "Occitan (post 1500)", label: "Occitan (post 1500)" },
    { value: "Ojibwa", label: "Ojibwa" },
    { value: "Oriya", label: "Oriya" },
    { value: "Oromo", label: "Oromo" },
    { value: "Ossetian, Ossetic", label: "Ossetian, Ossetic" },
    { value: "Pali", label: "Pali" },
    { value: "Panjabi, Punjabi", label: "Panjabi, Punjabi" },
    { value: "Pashto, Pushto", label: "Pashto, Pushto" },
    { value: "Persian", label: "Persian" },
    { value: "Polish", label: "Polish" },
    { value: "Portuguese", label: "Portuguese" },
    { value: "Quechua", label: "Quechua" },
    { value: "Romansh", label: "Romansh" },
    { value: "Rundi", label: "Rundi" },
    { value: "Russian", label: "Russian" },
    { value: "Samoan", label: "Samoan" },
    { value: "Sango", label: "Sango" },
    { value: "Sanskrit", label: "Sanskrit" },
    { value: "Sardinian", label: "Sardinian" },
    { value: "Serbian", label: "Serbian" },
    { value: "Shona", label: "Shona" },
    { value: "Sindhi", label: "Sindhi" },
    { value: "Sinhala, Sinhalese", label: "Sinhala, Sinhalese" },
    { value: "Slovak", label: "Slovak" },
    { value: "Slovenian", label: "Slovenian" },
    { value: "Somali", label: "Somali" },
    { value: "Sotho, Southern", label: "Sotho, Southern" },
    { value: "South Ndebele", label: "South Ndebele" },
    { value: "Spanish, Castilian", label: "Spanish, Castilian" },
    { value: "Sundanese", label: "Sundanese" },
    { value: "Swahili", label: "Swahili" },
    { value: "Swati", label: "Swati" },
    { value: "Swedish", label: "Swedish" },
    { value: "Tagalog", label: "Tagalog" },
    { value: "Tahitian", label: "Tahitian" },
    { value: "Tajik", label: "Tajik" },
    { value: "Tamil", label: "Tamil" },
    { value: "Tatar", label: "Tatar" },
    { value: "Telugu", label: "Telugu" },
    { value: "Thai", label: "Thai" },
    { value: "Tibetan", label: "Tibetan" },
    { value: "Tigrinya", label: "Tigrinya" },
    { value: "Tonga (Tonga Islands)", label: "Tonga (Tonga Islands)" },
    { value: "Tsonga", label: "Tsonga" },
    { value: "Tswana", label: "Tswana" },
    { value: "Turkish", label: "Turkish" },
    { value: "Turkmen", label: "Turkmen" },
    { value: "Twi", label: "Twi" },
    { value: "Uighur, Uyghur", label: "Uighur, Uyghur" },
    { value: "Ukrainian", label: "Ukrainian" },
    { value: "Urdu", label: "Urdu" },
    { value: "Uzbek", label: "Uzbek" },
    { value: "Venda", label: "Venda" },
    { value: "Vietlabelse", label: "Vietlabelse" },
    { value: "Volap_k", label: "Volap_k" },
    { value: "Walloon", label: "Walloon" },
    { value: "Welsh", label: "Welsh" },
    { value: "Western Frisian", label: "Western Frisian" },
    { value: "Wolof", label: "Wolof" },
    { value: "Xhosa", label: "Xhosa" },
    { value: "Yiddish", label: "Yiddish" },
    { value: "Yoruba", label: "Yoruba" },
    { value: "Zhuang, Chuang", label: "Zhuang, Chuang" },
    { value: "Zulu", label: "Zulu" }
];

export const TEXTOPTIONS = [
    'Construction Worker',
    'Social Worker',
    'Business Owner',
    'Veterinarian',
    'Photographer',
    'Equipment Operator',
    'Videographer',
    'Firefighter',
    'Mathematician',
    'Computer Scientist',
    'Hair Stylist',
    'Executive Manager',
    'Surveyor',
    'Software Developer',
    'Hospitality Worker',
    'Medical Professional',
    'Mechanic',
];

export const HASHTAG = [
    { value: "love", label: "love" },
    { value: "instagood", label: "instagood" },
    { value: "fashion", label: "fashion" },
    { value: "photooftheday", label: "photooftheday" },
    { value: "beautiful", label: "beautiful" },
    { value: "art", label: "art" },
    { value: "photography", label: "photography" },
    { value: "happy", label: "happy" },
    { value: "picoftheday", label: "picoftheday" },
    { value: "cute", label: "cute" },
    { value: "follow", label: "follow" },
    { value: "tbt", label: "tbt" },
    { value: "followme", label: "followme" },
    { value: "nature", label: "nature" },
    { value: "like4like", label: "like4like" },
    { value: "travel", label: "travel" },
    { value: "instagram", label: "instagram" },
    { value: "style", label: "style" },
    { value: "repost", label: "repost" },
    { value: "summer", label: "summer" },
    { value: "instadaily", label: "instadaily" },
    { value: "selfie", label: "selfie" },
    { value: "me", label: "me" },
    { value: "friends", label: "friends" },
    { value: "fitness", label: "fitness" },
    { value: "girl", label: "girl" },
    { value: "food", label: "food" },
    { value: "fun", label: "fun" },
    { value: "beauty", label: "beauty" },
    { value: "instalike", label: "instalike" },
    { value: "smile", label: "smile" },
    { value: "family", label: "family" },
    { value: "photo", label: "photo" },
    { value: "life", label: "life" },
    { value: "likeforlike", label: "likeforlike" },
    { value: "music", label: "music" },
    { value: "ootd", label: "ootd" },
    { value: "follow4follow", label: "follow4follow" },
    { value: "makeup", label: "makeup" },
    { value: "amazing", label: "amazing" },
    { value: "igers", label: "igers" },
    { value: "nofilter", label: "nofilter" },
    { value: "dog", label: "dog" },
    { value: "model", label: "model" },
    { value: "sunset", label: "sunset" },
    { value: "beach", label: "beach" },
    { value: "instamood", label: "instamood" },
    { value: "foodporn", label: "foodporn" },
    { value: "motivation", label: "motivation" },
    { value: "followforfollow", label: "followforfollow" },
    { value: "business", label: "business" },
    { value: "entrepreneur", label: "entrepreneur" },
    { value: "success", label: "success" },
    { value: "onlineshop", label: "onlineshop" },
    { value: "smallbusiness", label: "smallbusiness" },
    { value: "marketing", label: "marketing" },
    { value: "branding", label: "branding" },
    { value: "marketingdigital", label: "marketingdigital" },
    { value: "innovation", label: "innovation" },
    { value: "ecommerce", label: "ecommerce" },
    { value: "retail", label: "retail" },
    { value: "onlinemarketing", label: "onlinemarketing" },
    { value: "contentmarketing", label: "contentmarketing" },
    { value: "marketingtips", label: "marketingtips" },
    { value: "marketingstrategy", label: "marketingstrategy" },
    { value: "startups", label: "startups" },
    { value: "management", label: "management" },
    { value: "businesstips", label: "businesstips" },
    { value: "software", label: "software" },
    { value: "B2B", label: "B2B" },
    { value: "instagramforbusiness", label: "instagramforbusiness" },
    { value: "b2bmarketing", label: "b2bmarketing" },
    { value: "eventmarketing", label: "eventmarketing" },
    { value: "b2bsales", label: "b2bsales" },
    { value: "training", label: "training" },
    { value: "sale", label: "sale" },
    { value: "onlineshopping", label: "onlineshopping" },
    { value: "promo", label: "promo" },
    { value: "socialmedia", label: "socialmedia" },
    { value: "digitalmarketing", label: "digitalmarketing" },
    { value: "startup", label: "startup" },
    { value: "socialmediamarketing", label: "socialmediamarketing" },
    { value: "sales", label: "sales" },
    { value: "advertising", label: "advertising" },
    { value: "networking", label: "networking" },
    { value: "onlinebusiness", label: "onlinebusiness" },
    { value: "smallbiz", label: "smallbiz" },
    { value: "company", label: "company" },
    { value: "startuplife", label: "startuplife" },
    { value: "socialmediatips", label: "socialmediatips" },
    { value: "marketplace", label: "marketplace" },
    { value: "b2c", label: "b2c" },
    { value: "b2cmarketing", label: "b2cmarketing" },
];

export const INTERESTS = [
    { value: "Animation", label: "Animation" },
    { value: "Architecture", label: "Architecture" },
    { value: "Calligraphy", label: "Calligraphy" },
    { value: "Candle making", label: "Candle making" },
    { value: "Cardmaking", label: "Cardmaking" },
    { value: "Ceramics", label: "Ceramics" },
    { value: "Crocheting", label: "Crocheting" },
    { value: "Drawing", label: "Drawing" },
    { value: "Embroidery", label: "Embroidery" },
    { value: "Fashion design", label: "Fashion design" },
    { value: "Filmmaking", label: "Filmmaking" },
    { value: "Floristry", label: "Floristry" },
    { value: "Furniture building", label: "Furniture building" },
    { value: "Gardening", label: "Gardening" },
    { value: "Glass painting", label: "Glass painting" },
    { value: "Home decorating", label: "Home decorating" },
    { value: "Jewelry making", label: "Jewelry making" },
    { value: "Knitting", label: "Knitting" },
    { value: "Origami", label: "Origami" },
    { value: "Painting", label: "Painting" },
    { value: "Photography", label: "Photography" },
    { value: "Quilling", label: "Quilling" },
    { value: "Quilting", label: "Quilting" },
    { value: "Scrapbooking", label: "Scrapbooking" },
    { value: "Sculpting", label: "Sculpting" },
    { value: "Sewing", label: "Sewing" },
    { value: "Sketching", label: "Sketching" },
    { value: "Soap making", label: "Soap making" },
    { value: "Pottery", label: "Pottery" },
    { value: "Woodburning", label: "Woodburning" },
    { value: "Woodcarving", label: "Woodcarving" },
    { value: "Woodworking", label: "Woodworking" },
    { value: "Collecting", label: "Collecting" },
    { value: "Action figures", label: "Action figures" },
    { value: "Amateur geology", label: "Amateur geology" },
    { value: "Antiques", label: "Antiques" },
    { value: "Autographs", label: "Autographs" },
    { value: "Cars", label: "Cars" },
    { value: "Coins", label: "Coins" },
    { value: "Comic books", label: "Comic books" },
    { value: "Dolls", label: "Dolls" },
    { value: "Fine art", label: "Fine art" },
    { value: "LEGO sets", label: "LEGO sets" },
    { value: "Model diecast cars", label: "Model diecast cars" },
    { value: "Movie memorabilia", label: "Movie memorabilia" },
    { value: "Music memorabilia", label: "Music memorabilia" },
    { value: "Sports memorabilia", label: "Sports memorabilia" },
    { value: "Sports trading cards", label: "Sports trading cards" },
    { value: "Stamps", label: "Stamps" },
    { value: "Vinyl records", label: "Vinyl records" },
    { value: "Watches", label: "Watches" },
    { value: "Food and drink", label: "Food and drink" },
    { value: "Baking", label: "Baking" },
    { value: "Bartending", label: "Bartending" },
    { value: "Beer tasting", label: "Beer tasting" },
    { value: "Brewing", label: "Brewing" },
    { value: "Coffee roasting", label: "Coffee roasting" },
    { value: "Cooking", label: "Cooking" },
    { value: "Grilling", label: "Grilling" },
    { value: "Mixology", label: "Mixology" },
    { value: "Sushi making", label: "Sushi making" },
    { value: "Whiskey tasting", label: "Whiskey tasting" },
    { value: "Wine making", label: "Wine making" },
    { value: "Wine tasting", label: "Wine tasting" },
    { value: "Games", label: "Games" },
    { value: "3D games", label: "3D games" },
    { value: "Arcade games", label: "Arcade games" },
    { value: "Billiards", label: "Billiards" },
    { value: "Board games", label: "Board games" },
    { value: "Bridge", label: "Bridge" },
    { value: "Card games", label: "Card games" },
    { value: "Chess", label: "Chess" },
    { value: "Crossword puzzles", label: "Crossword puzzles" },
    { value: "Dominoes", label: "Dominoes" },
    { value: "Geocaching", label: "Geocaching" },
    { value: "Jigsaw puzzles", label: "Jigsaw puzzles" },
    { value: "Sudoku", label: "Sudoku" },
    { value: "Table tennis", label: "Table tennis" },
    { value: "Video games", label: "Video games" },
    { value: "Word scrambles", label: "Word scrambles" },
    { value: "Model", label: "Model" },
    { value: "electronic and tech", label: "electronic and tech" },
    { value: "App building", label: "App building" },
    { value: "Blogging", label: "Blogging" },
    { value: "Car restoration", label: "Car restoration" },
    { value: "Model airplanes", label: "Model airplanes" },
    { value: "Model cars", label: "Model cars" },
    { value: "Model railroading", label: "Model railroading" },
    { value: "Model rockets", label: "Model rockets" },
    { value: "Model ships", label: "Model ships" },
    { value: "Podcasting", label: "Podcasting" },
    { value: "Programming / Coding", label: "Programming / Coding" },
    { value: "RC boats", label: "RC boats" },
    { value: "RC cars", label: "RC cars" },
    { value: "RC helicopters", label: "RC helicopters" },
    { value: "RC planes", label: "RC planes" },
    { value: "Robotics", label: "Robotics" },
    { value: "Scale miniature building", label: "Scale miniature building" },
    { value: "Web design", label: "Web design" },
    { value: "YouTubing", label: "YouTubing" },
    { value: "Music", label: "Music" },
    { value: "Choir singing", label: "Choir singing" },
    { value: "Composing music", label: "Composing music" },
    { value: "DJing", label: "DJing" },
    { value: "Mashups", label: "Mashups" },
    { value: "Opera", label: "Opera" },
    { value: "Playing a musical instrument", label: "Playing a musical instrument" },
    { value: "Rapping", label: "Rapping" },
    { value: "Singing", label: "Singing" },
    { value: "Performing arts", label: "Performing arts" },
    { value: "Acting", label: "Acting" },
    { value: "Ballet", label: "Ballet" },
    { value: "Breakdancing", label: "Breakdancing" },
    { value: "Historical reenactments", label: "Historical reenactments" },
    { value: "Juggling", label: "Juggling" },
    { value: "Line dancing", label: "Line dancing" },
    { value: "Magic tricks", label: "Magic tricks" },
    { value: "Puppetry", label: "Puppetry" },
    { value: "Salsa", label: "Salsa" },
    { value: "Standup comedy", label: "Standup comedy" },
    { value: "Swing", label: "Swing" },
    { value: "Tango", label: "Tango" },
    { value: "Waltz", label: "Waltz" },
    { value: "Pets and animals", label: "Pets and animals" },
    { value: "Animal breeding", label: "Animal breeding" },
    { value: "Animal rescue", label: "Animal rescue" },
    { value: "Animal training", label: "Animal training" },
    { value: "Beekeeping", label: "Beekeeping" },
    { value: "Dog walking", label: "Dog walking" },
    { value: "Fishkeeping", label: "Fishkeeping" },
    { value: "Pet fostering", label: "Pet fostering" },
    { value: "Pet grooming", label: "Pet grooming" },
    { value: "Spiritual and mental", label: "Spiritual and mental" },
    { value: "Astrology", label: "Astrology" },
    { value: "Astronomy", label: "Astronomy" },
    { value: "Freelance writing", label: "Freelance writing" },
    { value: "Genealogy", label: "Genealogy" },
    { value: "Journaling", label: "Journaling" },
    { value: "Languages", label: "Languages" },
    { value: "Meditation", label: "Meditation" },
    { value: "Neurolinguistic programming", label: "Neurolinguistic programming" },
    { value: "Novel writing", label: "Novel writing" },
    { value: "Online classes", label: "Online classes" },
    { value: "Play writing", label: "Play writing" },
    { value: "Poetry", label: "Poetry" },
    { value: "Reading", label: "Reading" },
    { value: "Screenwriting", label: "Screenwriting" },
    { value: "Sign language", label: "Sign language" },
    { value: "Songwriting", label: "Songwriting" },
    { value: "Speed reading", label: "Speed reading" },
    { value: "Volunteering", label: "Volunteering" },
    { value: "Sports and outdoors", label: "Sports and outdoors" },
    { value: "Acrobatics", label: "Acrobatics" },
    { value: "Archery", label: "Archery" },
    { value: "Badminton", label: "Badminton" },
    { value: "Backpacking travel", label: "Backpacking travel" },
    { value: "Base jumping", label: "Base jumping" },
    { value: "Baseball", label: "Baseball" },
    { value: "Basketball", label: "Basketball" },
    { value: "Birdwatching", label: "Birdwatching" },
    { value: "Bodybuilding", label: "Bodybuilding" },
    { value: "Bowling", label: "Bowling" },
    { value: "Boxing", label: "Boxing" },
    { value: "Camping", label: "Camping" },
    { value: "Canoeing", label: "Canoeing" },
    { value: "Croquet", label: "Croquet" },
    { value: "Cycling", label: "Cycling" },
    { value: "Darts", label: "Darts" },
    { value: "Diving", label: "Diving" },
    { value: "Fantasy football", label: "Fantasy football" },
    { value: "Fencing", label: "Fencing" },
    { value: "Figure skating", label: "Figure skating" },
    { value: "Fishing", label: "Fishing" },
    { value: "Flying", label: "Flying" },
    { value: "Football", label: "Football" },
    { value: "Go karting", label: "Go karting" },
    { value: "Golf", label: "Golf" },
    { value: "Gymnastics", label: "Gymnastics" },
    { value: "Hang gliding", label: "Hang gliding" },
    { value: "Hiking", label: "Hiking" },
    { value: "Horse racing", label: "Horse racing" },
    { value: "Horseback riding", label: "Horseback riding" },
    { value: "Ice skating", label: "Ice skating" },
    { value: "Kayaking", label: "Kayaking" },
    { value: "Marathon running", label: "Marathon running" },
    { value: "Martial arts", label: "Martial arts" },
    { value: "Mountain biking", label: "Mountain biking" },
    { value: "Mountaineering", label: "Mountaineering" },
    { value: "Paintball", label: "Paintball" },
    { value: "Paragliding", label: "Paragliding" },
    { value: "Pilates", label: "Pilates" },
    { value: "Rock climbing", label: "Rock climbing" },
    { value: "Running", label: "Running" },
    { value: "RV traveling", label: "RV traveling" },
    { value: "Sailing", label: "Sailing" },
    { value: "Scuba diving", label: "Scuba diving" },
    { value: "Sightseeing", label: "Sightseeing" },
    { value: "Skateboarding", label: "Skateboarding" },
    { value: "Skiing", label: "Skiing" },
    { value: "Skydiving", label: "Skydiving" },
    { value: "Snowboarding", label: "Snowboarding" },
    { value: "Squash", label: "Squash" },
    { value: "Surfing", label: "Surfing" },
    { value: "Swimming", label: "Swimming" },
    { value: "Tennis", label: "Tennis" },
    { value: "Travel", label: "Travel" },
    { value: "Water skiing", label: "Water skiing" },
    { value: "Weight training", label: "Weight training" },
    { value: "Windsurfing", label: "Windsurfing" },
    { value: "Yoga", label: "Yoga" }
];

export const SKILLS = [
    { "value": "Building Information Modelling", "label": "Building Information Modelling" },
    { "value": "Project Management", "label": "Project Management" },
    { "value": "Risk Management", "label": "Risk Management" },
    { "value": "Management", "label": "Management" },
    { "value": "Customer Service", "label": "Customer Service" },
    { "value": "Auditing", "label": "Auditing" },
    { "value": "Leadership", "label": "Leadership" },
    { "value": "Internal Controls", "label": "Internal Controls" },
    { "value": "Training", "label": "Training" },
    { "value": "Business Analysis", "label": "Business Analysis" },
    { "value": "Finance", "label": "Finance" },
    { "value": "Project Planning", "label": "Project Planning" },
    { "value": "Analysis", "label": "Analysis" },
    { "value": "Internal Audit", "label": "Internal Audit" },
    { "value": "Employee Relations", "label": "Employee Relations" },
    { "value": "Security", "label": "Security" },
    { "value": "Strategy", "label": "Strategy" },
    { "value": "Coaching", "label": "Coaching" },
    { "value": "Governance", "label": "Governance" },
    { "value": "Banking", "label": "Banking" },
    { "value": "Business Planning", "label": "Business Planning" },
    { "value": "Budget Management", "label": "Budget Management" },
    { "value": "Strategic Planning", "label": "Strategic Planning" },
    { "value": "Team Leadership", "label": "Team Leadership" },
    { "value": "Communication", "label": "Communication" },
    { "value": "Team Management", "label": "Team Management" },
    { "value": "Time Management", "label": "Time Management" },
    { "value": "Program Management", "label": "Program Management" },
    { "value": "Problem Solving", "label": "Problem Solving" },
    { "value": "Business Development", "label": "Business Development" },
    { "value": "Digital Marketing", "label": "Digital Marketing" },
    { "value": "Change Management", "label": "Change Management" },
    { "value": "Microsoft Office", "label": "Microsoft Office" },
    { "value": "Agency Management", "label": "Agency Management" },
    { "value": "Advertising", "label": "Advertising" },
    { "value": "Process Improvement", "label": "Process Improvement" },
    { "value": "Vendor Management", "label": "Vendor Management" },
    { "value": "Financial Management", "label": "Financial Management" },
    { "value": "Financial Reporting", "label": "Financial Reporting" },
    { "value": "Public Speaking", "label": "Public Speaking" },
    { "value": "Marketing", "label": "Marketing" },
    { "value": "Accounting", "label": "Accounting" },
    { "value": "Negotiation", "label": "Negotiation" },
    { "value": "Financial Analysis", "label": "Financial Analysis" },
    { "value": "Business Strategy", "label": "Business Strategy" },
    { "value": "Teamwork", "label": "Teamwork" },
    { "value": "Operations Management", "label": "Operations Management" },
    { "value": "Supply Chain Management", "label": "Supply Chain Management" },
    { "value": "Contract Management", "label": "Contract Management" },
    { "value": "Engineering", "label": "Engineering" },
    { "value": "Logistics", "label": "Logistics" },
    { "value": "Purchasing", "label": "Purchasing" },
    { "value": "Contract Negotiation", "label": "Contract Negotiation" },
    { "value": "Supply Chain", "label": "Supply Chain" },
    { "value": "Budgets", "label": "Budgets" },
    { "value": "Networking", "label": "Networking" },
    { "value": "Operating Systems", "label": "Operating Systems" },
    { "value": "Virtualization", "label": "Virtualization" },
    { "value": "Cloud Computing", "label": "Cloud Computing" },
    { "value": "Linux", "label": "Linux" },
    { "value": "Databases", "label": "Databases" },
    { "value": "System Administration", "label": "System Administration" },
    { "value": "Data Center", "label": "Data Center" },
    { "value": "Network Security", "label": "Network Security" },
    { "value": "Windows Server", "label": "Windows Server" },
    { "value": "Integration", "label": "Integration" },
    { "value": "Windows", "label": "Windows" },
    { "value": "IT Management", "label": "IT Management" },
    { "value": "Active Directory", "label": "Active Directory" },
    { "value": "Troubleshooting", "label": "Troubleshooting" },
    { "value": "Servers", "label": "Servers" },
    { "value": "Disaster Recovery", "label": "Disaster Recovery" },
    { "value": "SQL", "label": "SQL" },
    { "value": "Java", "label": "Java" },
    { "value": "Python", "label": "Python" },
    { "value": "C++", "label": "C++" },
    { "value": "Javascript", "label": "Javascript" },
    { "value": "C", "label": "C" },
    { "value": "MySQL", "label": "MySQL" },
    { "value": "Oracle", "label": "Oracle" },
    { "value": "XML", "label": "XML" },
    { "value": "Software Development", "label": "Software Development" },
    { "value": "Agile Methodologies", "label": "Agile Methodologies" },
    { "value": "Adobe Photoshop", "label": "Adobe Photoshop" },
    { "value": "Social Media", "label": "Social Media" },
    { "value": "AutoCAD", "label": "AutoCAD" },
    { "value": "Photoshop", "label": "Photoshop" },
    { "value": "Photography", "label": "Photography" },
    { "value": "Wordpress", "label": "Wordpress" },
    { "value": "Sketchup", "label": "Sketchup" },
    { "value": "HTML", "label": "HTML" },
    { "value": "Illustrator", "label": "Illustrator" },
    { "value": "Microsoft Word", "label": "Microsoft Word" },
    { "value": "Microsoft Excel", "label": "Microsoft Excel" },
    { "value": "Indesign", "label": "Indesign" },
    { "value": "Presentation", "label": "Presentation" },
    { "value": "Dreamweaver", "label": "Dreamweaver" },
    { "value": "2D & 3D Animation", "label": "2D & 3D Animation" },
    { "value": "Flash", "label": "Flash" },
    { "value": "Powerpoint", "label": "Powerpoint" },
    { "value": "Premiere", "label": "Premiere" },
    { "value": "Excel", "label": "Excel" },
    { "value": "Revit", "label": "Revit" },
    { "value": "Quark", "label": "Quark" },
    { "value": "Distributed Architectures", "label": "Distributed Architectures" },
    { "value": "Autocad", "label": "Autocad" },
    { "value": "SOA", "label": "SOA" },
    { "value": "API Integration", "label": "API Integration" },
    { "value": "Architectural Design", "label": "Architectural Design" },
    { "value": "Web Applications", "label": "Web Applications" },
    { "value": "Enterprise Architecture", "label": "Enterprise Architecture" },
    { "value": "Web Services", "label": "Web Services" },
    { "value": "Scrum", "label": "Scrum" },
    { "value": "Software Engineering", "label": "Software Engineering" },
    { "value": "Programming", "label": "Programming" },
    { "value": "CAD", "label": "CAD" },
    { "value": "Rendering", "label": "Rendering" },
    { "value": "GD&T", "label": "GD&T" },
    { "value": "FEA", "label": "FEA" },
    { "value": "Construction", "label": "Construction" },
    { "value": "DFMA", "label": "DFMA" },
    { "value": "Solidworks", "label": "Solidworks" },
    { "value": "Design", "label": "Design" },
    { "value": "User Experience Design", "label": "User Experience Design" },
    { "value": "User Interface Design", "label": "User Interface Design" },
    { "value": "AR/VR", "label": "AR/VR" },
    { "value": "Game Development", "label": "Game Development" },
    { "value": "Application Development", "label": "Application Development" },
    { "value": "Writing", "label": "Writing" },
    { "value": "Database", "label": "Database" },
    { "value": "Drawing", "label": "Drawing" },
    { "value": "Painting", "label": "Painting" },
    { "value": "Graphic Design", "label": "Graphic Design" },
    { "value": "Illustration", "label": "Illustration" },
    { "value": "Sketching", "label": "Sketching" },
    { "value": "InDesign", "label": "InDesign" },
    { "value": "CSS", "label": "CSS" },
    { "value": "PHP", "label": "PHP" },
    { "value": "After Effects", "label": "After Effects" },
    { "value": "How to List Photos", "label": "How to List Photos" },
    { "value": "Video Editing", "label": "Video Editing" },
    { "value": "Final Cut Pro", "label": "Final Cut Pro" },
    { "value": "Video", "label": "Video" },
    { "value": "Ms Powerpoint", "label": "Ms Powerpoint" },
    { "value": "Ms Word", "label": "Ms Word" },
    { "value": "Adobe Page Maker", "label": "Adobe Page Maker" },
    { "value": "Editing", "label": "Editing" },
    { "value": "Television", "label": "Television" },
    { "value": "Social Media Marketing", "label": "Social Media Marketing" },
    { "value": "Adobe Creative Suite", "label": "Adobe Creative Suite" },
    { "value": "Digital Media", "label": "Digital Media" },
    { "value": "Public Relations", "label": "Public Relations" },
    { "value": "Product Development", "label": "Product Development" },
    { "value": "Product Management", "label": "Product Management" },
    { "value": "User Experience", "label": "User Experience" },
    { "value": "Concept Design", "label": "Concept Design" },
    { "value": "Product Marketing", "label": "Product Marketing" },
    { "value": "Entrepreneurship", "label": "Entrepreneurship" },
    { "value": "Web Design", "label": "Web Design" },
    { "value": "Industrial Design", "label": "Industrial Design" },
    { "value": "Business Management", "label": "Business Management" },
    { "value": "Microsoft Office Suite", "label": "Microsoft Office Suite" },
    { "value": "Finance/Accounting/Payroll", "label": "Finance/Accounting/Payroll" },
    { "value": "Client Relations", "label": "Client Relations" },
    { "value": "Relationship Management", "label": "Relationship Management" },
    { "value": "Web Analytics", "label": "Web Analytics" },
    { "value": "Content Marketing", "label": "Content Marketing" },
    { "value": "Computer Skills", "label": "Computer Skills" },
    { "value": "Customer Service Management", "label": "Customer Service Management" },
    { "value": "Creative", "label": "Creative" },
    { "value": "Goal Oriented", "label": "Goal Oriented" },
    { "value": "Community Management", "label": "Community Management" },
    { "value": "Physics", "label": "Physics" },
    { "value": "English", "label": "English" },
    { "value": "Data Analysis", "label": "Data Analysis" },
    { "value": "Machine Learning", "label": "Machine Learning" },
    { "value": "Adaptability", "label": "Adaptability" },
    { "value": "Computer Science", "label": "Computer Science" },
    { "value": "Construction Management", "label": "Construction Management" },
    { "value": "Project Controls", "label": "Project Controls" },
    { "value": "Creativity", "label": "Creativity" },
    { "value": "Organization", "label": "Organization" },
    { "value": "Competitive Analysis", "label": "Competitive Analysis" },
    { "value": "Marketing Strategy", "label": "Marketing Strategy" },
    { "value": "Sales", "label": "Sales" },
    { "value": "Basic Theory", "label": "Basic Theory" },
    { "value": "Object-Oriented Programming", "label": "Object-Oriented Programming" },
    { "value": "Research", "label": "Research" },
    { "value": "R", "label": "R" },
    { "value": "Matlab", "label": "Matlab" },
    { "value": "SPSS", "label": "SPSS" },
    { "value": "Data Visualization", "label": "Data Visualization" },
    { "value": "Hive", "label": "Hive" },
    { "value": "Spark", "label": "Spark" },
    { "value": "Tableau", "label": "Tableau" },
    { "value": "Mongodb", "label": "Mongodb" },
    { "value": "Git", "label": "Git" },
    { "value": "Big Data", "label": "Big Data" },
    { "value": "Scala", "label": "Scala" },
    { "value": "Hadoop", "label": "Hadoop" },
    { "value": "Kafka", "label": "Kafka" },
    { "value": "AWS", "label": "AWS" },
    { "value": "Mlib", "label": "Mlib" },
    { "value": "Sqoop", "label": "Sqoop" },
    { "value": "Mapreduce", "label": "Mapreduce" },
    { "value": "Docker", "label": "Docker" },
    { "value": "Hbase", "label": "Hbase" },
    { "value": "MongoDB", "label": "MongoDB" },
    { "value": "Database Management", "label": "Database Management" },
    { "value": "ETL", "label": "ETL" },
    { "value": "Data Modelling", "label": "Data Modelling" },
    { "value": "Data", "label": "Data" },
    { "value": "Reporting", "label": "Reporting" },
    { "value": "Problem-Solving", "label": "Problem-Solving" },
    { "value": "Leadership And Management", "label": "Leadership And Management" },
    { "value": "Data Visualisation", "label": "Data Visualisation" },
    { "value": "Business Intelligence Dashboards", "label": "Business Intelligence Dashboards" },
    { "value": "Business Intelligence", "label": "Business Intelligence" },
    { "value": "Programming Languages", "label": "Programming Languages" },
    { "value": "Operating System", "label": "Operating System" },
    { "value": "Development Tools", "label": "Development Tools" },
    { "value": "Web Technologies", "label": "Web Technologies" },
    { "value": "Web Development", "label": "Web Development" },
    { "value": "Frameworks", "label": "Frameworks" },
    { "value": "Applications", "label": "Applications" },
    { "value": "Version Control", "label": "Version Control" },
    { "value": "ArcGIS", "label": "ArcGIS" },
    { "value": "Sigma Plot", "label": "Sigma Plot" },
    { "value": "Market Analysis", "label": "Market Analysis" },
    { "value": "Qualitative Research", "label": "Qualitative Research" },
    { "value": "Data Management", "label": "Data Management" },
    { "value": "Report Writing", "label": "Report Writing" },
    { "value": "Quantitative Research", "label": "Quantitative Research" },
    { "value": "Academic Writing", "label": "Academic Writing" },
    { "value": "Research Design", "label": "Research Design" },
    { "value": "Proofreading", "label": "Proofreading" },
    { "value": "Content Management System", "label": "Content Management System" },
    { "value": "Blogging", "label": "Blogging" },
    { "value": "Teaching", "label": "Teaching" },
    { "value": "Copywriting", "label": "Copywriting" },
    { "value": "Foreign Languages", "label": "Foreign Languages" },
    { "value": "React", "label": "React" },
    { "value": "Typescript", "label": "Typescript" },
    { "value": "C#", "label": "C#" },
    { "value": "JQuery", "label": "JQuery" },
    { "value": "Node.Js", "label": "Node.Js" },
    { "value": "Bootstrap", "label": "Bootstrap" },
    { "value": "HTML5", "label": "HTML5" },
    { "value": "Testing", "label": "Testing" },
    { "value": "Embedded Systems", "label": "Embedded Systems" },
    { "value": "Embedded C", "label": "Embedded C" },
    { "value": "Coding", "label": "Coding" },
    { "value": "Embedded Software", "label": "Embedded Software" },
    { "value": "Algorithms", "label": "Algorithms" },
    { "value": "Continuous Integration", "label": "Continuous Integration" },
    { "value": "Frontend", "label": "Frontend" },
    { "value": "Backend", "label": "Backend" },
    { "value": "Front-End", "label": "Front-End" },
    { "value": "Data Warehousing", "label": "Data Warehousing" },
    { "value": "Database Design", "label": "Database Design" },
    { "value": "Data Modeling", "label": "Data Modeling" },
    { "value": "Microsoft Sql Server", "label": "Microsoft Sql Server" },
    { "value": "Requirements Analysis", "label": "Requirements Analysis" },
    { "value": "Unix", "label": "Unix" },
    { "value": "Android", "label": "Android" },
    { "value": "GIT", "label": "GIT" },
    { "value": "CSS3", "label": "CSS3" },
    { "value": "Wireframing", "label": "Wireframing" },
    { "value": "UX Design", "label": "UX Design" },
    { "value": "Usability Testing", "label": "Usability Testing" },
    { "value": "Information Architecture", "label": "Information Architecture" },
    { "value": "Visual Design", "label": "Visual Design" },
    { "value": "Figma", "label": "Figma" },
    { "value": "User Research", "label": "User Research" },
    { "value": "UI Design", "label": "UI Design" },
    { "value": "Interaction Design", "label": "Interaction Design" },
    { "value": "Lumion", "label": "Lumion" },
    { "value": "Ms Office", "label": "Ms Office" },
    { "value": "3ds Max", "label": "3ds Max" },
    { "value": "Archicad", "label": "Archicad" },
    { "value": "3d Max", "label": "3d Max" },
    { "value": "Rhino", "label": "Rhino" },
    { "value": "Adobe Illustrator", "label": "Adobe Illustrator" },
    { "value": "Etabs", "label": "Etabs" },
    { "value": "OOP", "label": "OOP" },
    { "value": "Design Patterns", "label": "Design Patterns" },
    { "value": "Sql", "label": "Sql" },
    { "value": "jQuery", "label": "jQuery" },
    { "value": "TDD", "label": "TDD" },
    { "value": ".NET", "label": ".NET" },
    { "value": "UML", "label": "UML" },
    { "value": "Winforms", "label": "Winforms" },
    { "value": "Linq", "label": "Linq" },
    { "value": "WPF", "label": "WPF" },
    { "value": "UX", "label": "UX" },
    { "value": "IDE", "label": "IDE" },
    { "value": "Ruby On Rails", "label": "Ruby On Rails" },
    { "value": "Jquery", "label": "Jquery" },
    { "value": "React.Js", "label": "React.Js" },
    { "value": "DevOps", "label": "DevOps" },
    { "value": "React Native", "label": "React Native" },
    { "value": "Solidity", "label": "Solidity" },
    { "value": "Ethereum", "label": "Ethereum" },
    { "value": "Vue.Js", "label": "Vue.Js" },
    { "value": "Laravel", "label": "Laravel" },
    { "value": "Ruby", "label": "Ruby" },
    { "value": "Postgresql3", "label": "Postgresql3" },
    { "value": "Data Science", "label": "Data Science" },
    { "value": "Continuous Improvement", "label": "Continuous Improvement" },
    { "value": "Lean Manufacturing", "label": "Lean Manufacturing" },
    { "value": "Vehicles", "label": "Vehicles" },
    { "value": "Manufacturing", "label": "Manufacturing" },
    { "value": "Sales Management", "label": "Sales Management" },
    { "value": "Customer Satisfaction", "label": "Customer Satisfaction" },
    { "value": "New Business Development", "label": "New Business Development" },
    { "value": "Kaizen", "label": "Kaizen" },
    { "value": "Team Building", "label": "Team Building" },
    { "value": "Welding", "label": "Welding" },
    { "value": "HVAC", "label": "HVAC" },
    { "value": "Mechanical", "label": "Mechanical" },
    { "value": "Carpentry", "label": "Carpentry" },
    { "value": "Electronics", "label": "Electronics" },
    { "value": "Instrumentation", "label": "Instrumentation" },
    { "value": "Computer", "label": "Computer" },
    { "value": "Automation", "label": "Automation" },
    { "value": "Mechanics", "label": "Mechanics" },
    { "value": "Software", "label": "Software" },
    { "value": "Assembly Language", "label": "Assembly Language" },
    { "value": "Hardware Design", "label": "Hardware Design" },
    { "value": "RTOS", "label": "RTOS" },
    { "value": "Technical Support", "label": "Technical Support" },
    { "value": "Six Sigma", "label": "Six Sigma" },
    { "value": "Ajax", "label": "Ajax" },
    { "value": "Microsoft SQL Server", "label": "Microsoft SQL Server" },
    { "value": "SAP", "label": "SAP" },
    { "value": "ASP.NET", "label": "ASP.NET" },
    { "value": "Clean Architecture", "label": "Clean Architecture" },
    { "value": "Html5", "label": "Html5" },
    { "value": "Modular front-end", "label": "Modular front-end" },
    { "value": "Angular", "label": "Angular" },
    { "value": "CSS Selectors", "label": "CSS Selectors" },
    { "value": "Redux", "label": "Redux" },
    { "value": "DOM", "label": "DOM" },
    { "value": "JSX", "label": "JSX" },
    { "value": "Arduino", "label": "Arduino" },
    { "value": "Computer Vision", "label": "Computer Vision" },
    { "value": "Software Programming Languages", "label": "Software Programming Languages" },
    { "value": "Java/JavaEE Technologies", "label": "Java/JavaEE Technologies" },
    { "value": "Software Architecture", "label": "Software Architecture" },
    { "value": "Electrical", "label": "Electrical" },
    { "value": "Machining", "label": "Machining" },
    { "value": "Plumbing", "label": "Plumbing" },
    { "value": "Fabrication", "label": "Fabrication" },
    { "value": "Mechanic", "label": "Mechanic" },
    { "value": "Forklift", "label": "Forklift" },
    { "value": "Metal Fabrication", "label": "Metal Fabrication" },
    { "value": "Blueprint Reading", "label": "Blueprint Reading" },
    { "value": "C API", "label": "C API" },
    { "value": "GTK", "label": "GTK" },
    { "value": "Debugging tools", "label": "Debugging tools" },
    { "value": "ALSA", "label": "ALSA" },
    { "value": "Boost", "label": "Boost" },
    { "value": "POCO", "label": "POCO" },
    { "value": "Qt", "label": "Qt" },
    { "value": "GCC", "label": "GCC" },
    { "value": "ICC", "label": "ICC" },
    { "value": "MS Access", "label": "MS Access" },
    { "value": "MS Powerpoint", "label": "MS Powerpoint" },
    { "value": "SAS", "label": "SAS" },
    { "value": "Electrical Engineering", "label": "Electrical Engineering" },
    { "value": "Commissioning", "label": "Commissioning" },
    { "value": "Scada", "label": "Scada" },
    { "value": "PLC", "label": "PLC" },
    { "value": "Enterprise Software", "label": "Enterprise Software" },
    { "value": "CRM", "label": "CRM" },
    { "value": "Pre-Sales", "label": "Pre-Sales" },
    { "value": "Cloud Platforms", "label": "Cloud Platforms" },
    { "value": "Containerization Platforms", "label": "Containerization Platforms" },
    { "value": "Virtualization Platforms", "label": "Virtualization Platforms" },
    { "value": "Automation And Orchestration", "label": "Automation And Orchestration" },
    { "value": "Development And Scripting", "label": "Development And Scripting" },
    { "value": "Linux Platforms", "label": "Linux Platforms" },
    { "value": "Windows Platforms", "label": "Windows Platforms" },
    { "value": "Packet Capture", "label": "Packet Capture" },
    { "value": "Devops", "label": "Devops" },
    { "value": "Cloud", "label": "Cloud" },
    { "value": "Warehouse Management", "label": "Warehouse Management" },
    { "value": "Languages", "label": "Languages" },
    { "value": "Transportation Management", "label": "Transportation Management" },
    { "value": "ETL Tools", "label": "ETL Tools" },
    { "value": "Process Development", "label": "Process Development" },
    { "value": "Customer Relationship", "label": "Customer Relationship" },
    { "value": "Key Accounts Management", "label": "Key Accounts Management" },
    { "value": "Distribution Management", "label": "Distribution Management" },
    { "value": "Microsoft Access", "label": "Microsoft Access" },
    { "value": "Microsoft Power Point", "label": "Microsoft Power Point" },
    { "value": "Office 365", "label": "Office 365" },
    { "value": "Spreadsheet", "label": "Spreadsheet" },
    { "value": "Pivot tables", "label": "Pivot tables" },
    { "value": "Document Management", "label": "Document Management" },
    { "value": "Communication Skills", "label": "Communication Skills" },
    { "value": "Talent Management", "label": "Talent Management" },
    { "value": "ADM", "label": "ADM" },
    { "value": "MS Office", "label": "MS Office" },
    { "value": "Payroll", "label": "Payroll" },
    { "value": "Departments", "label": "Departments" },
    { "value": "Growth", "label": "Growth" },
    { "value": "System", "label": "System" },
    { "value": "Organizational Development", "label": "Organizational Development" },
    { "value": "Revenue Analysis", "label": "Revenue Analysis" }
];