export const LANGUAGES = [
    { value: "Abkhazian", label: "Abkhazian" },
    { value: "Afar", label: "Afar" },
    { value: "Afrikaans", label: "Afrikaans" },
    { value: "Akan", label: "Akan" },
    { value: "Albanian", label: "Albanian" },
    { value: "Amharic", label: "Amharic" },
    { value: "Arabic", label: "Arabic" },
    { value: "Aragonese", label: "Aragonese" },
    { value: "Armenian", label: "Armenian" },
    { value: "Assamese", label: "Assamese" },
    { value: "Avaric", label: "Avaric" },
    { value: "Avestan", label: "Avestan" },
    { value: "Aymara", label: "Aymara" },
    { value: "Azerbaijani", label: "Azerbaijani" },
    { value: "Bambara", label: "Bambara" },
    { value: "Bashkir", label: "Bashkir" },
    { value: "Basque", label: "Basque" },
    { value: "Belarusian", label: "Belarusian" },
    { value: "Bengali", label: "Bengali" },
    { value: "Bihari languages", label: "Bihari languages" },
    { value: "Bislama", label: "Bislama" },
    { value: "Bosnian", label: "Bosnian" },
    { value: "Breton", label: "Breton" },
    { value: "Bulgarian", label: "Bulgarian" },
    { value: "Burmese", label: "Burmese" },
    { value: "Cantonese", label: "Cantonese" },
    { value: "Catalan, Valencian", label: "Catalan, Valencian" },
    { value: "Central Khmer", label: "Central Khmer" },
    { value: "Chamorro", label: "Chamorro" },
    { value: "Chechen", label: "Chechen" },
    { value: "Chichewa, Chewa, Nyanja", label: "Chichewa, Chewa, Nyanja" },
    { value: "Church Slavonic, Old Bulgarian, Old Church Slavonic", label: "Church Slavonic, Old Bulgarian, Old Church Slavonic" },
    { value: "Chuvash", label: "Chuvash" },
    { value: "Cornish", label: "Cornish" },
    { value: "Corsican", label: "Corsican" },
    { value: "Cree", label: "Cree" },
    { value: "Croatian", label: "Croatian" },
    { value: "Czech", label: "Czech" },
    { value: "Danish", label: "Danish" },
    { value: "Divehi, Dhivehi, Maldivian", label: "Divehi, Dhivehi, Maldivian" },
    { value: "Dutch, Flemish", label: "Dutch, Flemish" },
    { value: "Dzongkha", label: "Dzongkha" },
    { value: "English", label: "English" },
    { value: "Esperanto", label: "Esperanto" },
    { value: "Estonian", label: "Estonian" },
    { value: "Ewe", label: "Ewe" },
    { value: "Faroese", label: "Faroese" },
    { value: "Fijian", label: "Fijian" },
    { value: "Finnish", label: "Finnish" },
    { value: "French", label: "French" },
    { value: "Fulah", label: "Fulah" },
    { value: "Gaelic, Scottish Gaelic", label: "Gaelic, Scottish Gaelic" },
    { value: "Galician", label: "Galician" },
    { value: "Ganda", label: "Ganda" },
    { value: "Georgian", label: "Georgian" },
    { value: "German", label: "German" },
    { value: "Gikuyu, Kikuyu", label: "Gikuyu, Kikuyu" },
    { value: "Greek (Modern)", label: "Greek (Modern)" },
    { value: "Greenlandic, Kalaallisut", label: "Greenlandic, Kalaallisut" },
    { value: "Guarani", label: "Guarani" },
    { value: "Gujarati", label: "Gujarati" },
    { value: "Haitian, Haitian Creole", label: "Haitian, Haitian Creole" },
    { value: "Hausa", label: "Hausa" },
    { value: "Hebrew", label: "Hebrew" },
    { value: "Herero", label: "Herero" },
    { value: "Hindi", label: "Hindi" },
    { value: "Hiri Motu", label: "Hiri Motu" },
    { value: "Hungarian", label: "Hungarian" },
    { value: "Icelandic", label: "Icelandic" },
    { value: "Ido", label: "Ido" },
    { value: "Igbo", label: "Igbo" },
    { value: "Indonesian", label: "Indonesian" },
    { value: "Interlingua (International Auxiliary Language Association)", label: "Interlingua (International Auxiliary Language Association)" },
    { value: "Interlingue", label: "Interlingue" },
    { value: "Inuktitut", label: "Inuktitut" },
    { value: "Inupiaq", label: "Inupiaq" },
    { value: "Irish", label: "Irish" },
    { value: "Italian", label: "Italian" },
    { value: "Japanese", label: "Japanese" },
    { value: "Javanese", label: "Javanese" },
    { value: "Kannada", label: "Kannada" },
    { value: "Kanuri", label: "Kanuri" },
    { value: "Kashmiri", label: "Kashmiri" },
    { value: "Kazakh", label: "Kazakh" },
    { value: "Kinyarwanda", label: "Kinyarwanda" },
    { value: "Komi", label: "Komi" },
    { value: "Kongo", label: "Kongo" },
    { value: "Korean", label: "Korean" },
    { value: "Kwanyama, Kuanyama", label: "Kwanyama, Kuanyama" },
    { value: "Kurdish", label: "Kurdish" },
    { value: "Kyrgyz", label: "Kyrgyz" },
    { value: "Lao", label: "Lao" },
    { value: "Latin", label: "Latin" },
    { value: "Latvian", label: "Latvian" },
    { value: "Letzeburgesch, Luxembourgish", label: "Letzeburgesch, Luxembourgish" },
    { value: "Limburgish, Limburgan, Limburger", label: "Limburgish, Limburgan, Limburger" },
    { value: "Lingala", label: "Lingala" },
    { value: "Lithuanian", label: "Lithuanian" },
    { value: "Luba-Katanga", label: "Luba-Katanga" },
    { value: "Mandarin", label: "Mandarin" },
    { value: "Macedonian", label: "Macedonian" },
    { value: "Malagasy", label: "Malagasy" },
    { value: "Malay", label: "Malay" },
    { value: "Malayalam", label: "Malayalam" },
    { value: "Maltese", label: "Maltese" },
    { value: "Manx", label: "Manx" },
    { value: "Maori", label: "Maori" },
    { value: "Marathi", label: "Marathi" },
    { value: "Marshallese", label: "Marshallese" },
    { value: "Moldovan, Moldavian, Romanian", label: "Moldovan, Moldavian, Romanian" },
    { value: "Mongolian", label: "Mongolian" },
    { value: "Nauru", label: "Nauru" },
    { value: "Navajo, Navaho", label: "Navajo, Navaho" },
    { value: "Northern Ndebele", label: "Northern Ndebele" },
    { value: "Ndonga", label: "Ndonga" },
    { value: "Nepali", label: "Nepali" },
    { value: "Northern Sami", label: "Northern Sami" },
    { value: "Norwegian", label: "Norwegian" },
    { value: "Norwegian Bokmål", label: "Norwegian Bokmål" },
    { value: "Norwegian Nynorsk", label: "Norwegian Nynorsk" },
    { value: "Nuosu, Sichuan Yi", label: "Nuosu, Sichuan Yi" },
    { value: "Occitan (post 1500)", label: "Occitan (post 1500)" },
    { value: "Ojibwa", label: "Ojibwa" },
    { value: "Oriya", label: "Oriya" },
    { value: "Oromo", label: "Oromo" },
    { value: "Ossetian, Ossetic", label: "Ossetian, Ossetic" },
    { value: "Pali", label: "Pali" },
    { value: "Panjabi, Punjabi", label: "Panjabi, Punjabi" },
    { value: "Pashto, Pushto", label: "Pashto, Pushto" },
    { value: "Persian", label: "Persian" },
    { value: "Polish", label: "Polish" },
    { value: "Portuguese", label: "Portuguese" },
    { value: "Quechua", label: "Quechua" },
    { value: "Romansh", label: "Romansh" },
    { value: "Rundi", label: "Rundi" },
    { value: "Russian", label: "Russian" },
    { value: "Samoan", label: "Samoan" },
    { value: "Sango", label: "Sango" },
    { value: "Sanskrit", label: "Sanskrit" },
    { value: "Sardinian", label: "Sardinian" },
    { value: "Serbian", label: "Serbian" },
    { value: "Shona", label: "Shona" },
    { value: "Sindhi", label: "Sindhi" },
    { value: "Sinhala, Sinhalese", label: "Sinhala, Sinhalese" },
    { value: "Slovak", label: "Slovak" },
    { value: "Slovenian", label: "Slovenian" },
    { value: "Somali", label: "Somali" },
    { value: "Sotho, Southern", label: "Sotho, Southern" },
    { value: "South Ndebele", label: "South Ndebele" },
    { value: "Spanish, Castilian", label: "Spanish, Castilian" },
    { value: "Sundanese", label: "Sundanese" },
    { value: "Swahili", label: "Swahili" },
    { value: "Swati", label: "Swati" },
    { value: "Swedish", label: "Swedish" },
    { value: "Tagalog", label: "Tagalog" },
    { value: "Tahitian", label: "Tahitian" },
    { value: "Tajik", label: "Tajik" },
    { value: "Tamil", label: "Tamil" },
    { value: "Tatar", label: "Tatar" },
    { value: "Telugu", label: "Telugu" },
    { value: "Thai", label: "Thai" },
    { value: "Tibetan", label: "Tibetan" },
    { value: "Tigrinya", label: "Tigrinya" },
    { value: "Tonga (Tonga Islands)", label: "Tonga (Tonga Islands)" },
    { value: "Tsonga", label: "Tsonga" },
    { value: "Tswana", label: "Tswana" },
    { value: "Turkish", label: "Turkish" },
    { value: "Turkmen", label: "Turkmen" },
    { value: "Twi", label: "Twi" },
    { value: "Uighur, Uyghur", label: "Uighur, Uyghur" },
    { value: "Ukrainian", label: "Ukrainian" },
    { value: "Urdu", label: "Urdu" },
    { value: "Uzbek", label: "Uzbek" },
    { value: "Venda", label: "Venda" },
    { value: "Vietlabelse", label: "Vietlabelse" },
    { value: "Volap_k", label: "Volap_k" },
    { value: "Walloon", label: "Walloon" },
    { value: "Welsh", label: "Welsh" },
    { value: "Western Frisian", label: "Western Frisian" },
    { value: "Wolof", label: "Wolof" },
    { value: "Xhosa", label: "Xhosa" },
    { value: "Yiddish", label: "Yiddish" },
    { value: "Yoruba", label: "Yoruba" },
    { value: "Zhuang, Chuang", label: "Zhuang, Chuang" },
    { value: "Zulu", label: "Zulu" }
];

export const TEXTOPTIONS: Array<string> = [
    'Construction Worker',
    'Social Worker',
    'Business Owner',
    'Veterinarian',
    'Photographer',
    'Equipment Operator',
    'Videographer',
    'Firefighter',
    'Mathematician',
    'Computer Scientist',
    'Hair Stylist',
    'Executive Manager',
    'Surveyor',
    'Software Developer',
    'Hospitality Worker',
    'Medical Professional',
    'Mechanic',
];

export const HASHTAG = [
    { value: "love", label: "love" },
    { value: "instagood", label: "instagood" },
    { value: "fashion", label: "fashion" },
    { value: "photooftheday", label: "photooftheday" },
    { value: "beautiful", label: "beautiful" },
    { value: "art", label: "art" },
    { value: "photography", label: "photography" },
    { value: "happy", label: "happy" },
    { value: "picoftheday", label: "picoftheday" },
    { value: "cute", label: "cute" },
    { value: "follow", label: "follow" },
    { value: "tbt", label: "tbt" },
    { value: "followme", label: "followme" },
    { value: "nature", label: "nature" },
    { value: "like4like", label: "like4like" },
    { value: "travel", label: "travel" },
    { value: "instagram", label: "instagram" },
    { value: "style", label: "style" },
    { value: "repost", label: "repost" },
    { value: "summer", label: "summer" },
    { value: "instadaily", label: "instadaily" },
    { value: "selfie", label: "selfie" },
    { value: "me", label: "me" },
    { value: "friends", label: "friends" },
    { value: "fitness", label: "fitness" },
    { value: "girl", label: "girl" },
    { value: "food", label: "food" },
    { value: "fun", label: "fun" },
    { value: "beauty", label: "beauty" },
    { value: "instalike", label: "instalike" },
    { value: "smile", label: "smile" },
    { value: "family", label: "family" },
    { value: "photo", label: "photo" },
    { value: "life", label: "life" },
    { value: "likeforlike", label: "likeforlike" },
    { value: "music", label: "music" },
    { value: "ootd", label: "ootd" },
    { value: "follow4follow", label: "follow4follow" },
    { value: "makeup", label: "makeup" },
    { value: "amazing", label: "amazing" },
    { value: "igers", label: "igers" },
    { value: "nofilter", label: "nofilter" },
    { value: "dog", label: "dog" },
    { value: "model", label: "model" },
    { value: "sunset", label: "sunset" },
    { value: "beach", label: "beach" },
    { value: "instamood", label: "instamood" },
    { value: "foodporn", label: "foodporn" },
    { value: "motivation", label: "motivation" },
    { value: "followforfollow", label: "followforfollow" },
    { value: "business", label: "business" },
    { value: "entrepreneur", label: "entrepreneur" },
    { value: "success", label: "success" },
    { value: "onlineshop", label: "onlineshop" },
    { value: "smallbusiness", label: "smallbusiness" },
    { value: "marketing", label: "marketing" },
    { value: "branding", label: "branding" },
    { value: "marketingdigital", label: "marketingdigital" },
    { value: "innovation", label: "innovation" },
    { value: "ecommerce", label: "ecommerce" },
    { value: "retail", label: "retail" },
    { value: "onlinemarketing", label: "onlinemarketing" },
    { value: "contentmarketing", label: "contentmarketing" },
    { value: "marketingtips", label: "marketingtips" },
    { value: "marketingstrategy", label: "marketingstrategy" },
    { value: "startups", label: "startups" },
    { value: "management", label: "management" },
    { value: "businesstips", label: "businesstips" },
    { value: "software", label: "software" },
    { value: "B2B", label: "B2B" },
    { value: "instagramforbusiness", label: "instagramforbusiness" },
    { value: "b2bmarketing", label: "b2bmarketing" },
    { value: "eventmarketing", label: "eventmarketing" },
    { value: "b2bsales", label: "b2bsales" },
    { value: "training", label: "training" },
    { value: "sale", label: "sale" },
    { value: "onlineshopping", label: "onlineshopping" },
    { value: "promo", label: "promo" },
    { value: "socialmedia", label: "socialmedia" },
    { value: "digitalmarketing", label: "digitalmarketing" },
    { value: "startup", label: "startup" },
    { value: "socialmediamarketing", label: "socialmediamarketing" },
    { value: "sales", label: "sales" },
    { value: "advertising", label: "advertising" },
    { value: "networking", label: "networking" },
    { value: "onlinebusiness", label: "onlinebusiness" },
    { value: "smallbiz", label: "smallbiz" },
    { value: "company", label: "company" },
    { value: "startuplife", label: "startuplife" },
    { value: "socialmediatips", label: "socialmediatips" },
    { value: "marketplace", label: "marketplace" },
    { value: "b2c", label: "b2c" },
    { value: "b2cmarketing", label: "b2cmarketing" },
];